// Generated by Wrangler on Sat Aug 31 2024 04:10:34 GMT+0100 (West Africa Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  BUN_VERSION: '1.1.18';
  DB: D1Database;
}
