import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@components/providers';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { ThemeProvider } from 'next-themes';
import { Toast } from '@ui/toast';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} font-sans`}>
        <Providers>
          <ThemeProvider disableTransitionOnChange attribute="class">{children}</ThemeProvider>
          <Toast />
        </Providers>
      </body>
    </html>
  );
}
